# Generated by Django 4.0.4 on 2022-05-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Odo',
            field=models.IntegerField(default=0),
        ),
    ]
